var myName = "Alex";
var myAge = 32;
var canVote = true;
var anything = "dog";
anything = 2;
document.getElementById("tsStuff").innerHTML = "My name is " + myName;
document.write("canVote is a " + typeof (canVote) + "<br />");
document.write("myName is a " + typeof (myName) + "<br />");
document.write("anything is a " + typeof (anything) + "<br />");
var strToNumber = parseInt("5");
var numToString = 5;
document.write("numToString is a " + typeof (numToString.toString()) + "<br />");
